var string = {
    'en': {
        'title': "AnyPhone",
        'numberDefault': "555-333-6726",
        'enterPhone': "Please enter your phone number to log in.",
        'enterPhoneExtra': "This example is limited to 10-digit US number.",
        'buttonSubmit': "Continue",
        'buttonVerify': "Verify",
        'warningPhone': "You must enter a 10-digit US phone number including area code.",
        'warningTwilio': "Something went wrong. Please check your Twilio configuration.",
        'warningGeneral': "Something went wrong. Please try again.",
        'warningNoNumber': "You forgot to enter your mobile number.",
        'warningCodeLength': "You must enter a 4 digit code texted to your phone number.",
        'warningCodeInvalid': "That verification code is not valid.",
        'messageWelcomeDashboard': "Welcome to your Dashboard",
        'enterCode': "Enter the 4-digit confirmation code",
        'enterCodeExtra': "It was sent in an SMS message to",
        'emailLogin': "Your login code for AnyPhone is",
        'dashboardWelcome': "Welcome to your Dashboard",
        'dashboardNumber': "Your Number",
        'dashboardName': "Your Name",
        'dashboardNameHint': "Nick Fury",
        'dashboardSetting1': "Orbital Tracking Grid",
        'dashboardSetting2': "Iron Legion",
        'dashboardSetting3': "Theta Protocol",
        'dashboardUpdate': "Update",
        'dashboardFinished': "Are you finished?",
        'dashboardLogout': "Logout",
        'alertOK': "OK",
    },
    'ja': {
        'title': "AnyPhone - エニーフォン",
        'numberDefault': "090-1234-5678",
        'enterPhone': "ログインするには電話番号を入力してください。",
        'enterPhoneExtra': "この例は、米国の11桁と日本の10桁の番号に限定されています。",
        'buttonSubmit': "続ける",
        'buttonVerify': "確認",
        'warningPhone': "市外局番をまたは日本の11桁の電話番号を入力してください。",
        'warningTwilio': "問題が発生しました。お客様のTwilio設定を確認してください。",
        'warningGeneral': "問題が発生しました。もう一度試してください。",
        'warningNoNumber': "携帯番号の入力をお忘れです。",
        'warningCodeLength': "お客様の電話番号へ送信されたテキストメッセージに記載の4桁のコードを入力してください。",
        'warningCodeInvalid': "その確認コードは正しくありません。",
        'messageWelcomeDashboard': "ダッシュボードへようこそ。",
        'enterCode': "4桁の確認コードを入力してください",
        'enterCodeExtra': "SMSメッセージにてこちらへ送信されました",
        'emailLogin': "あなたのエニーフォンのログインコードは",
        'dashboardWelcome': "ダシボールド　へ　ようこそ",
        'dashboardNumber': "あなたのばんごう",
        'dashboardName': "あなたのなまえ",
        'dashboardNameHint': "ニーク　フューリー",
        'dashboardSetting1': "オービトル　ツラキング グリド",
        'dashboardSetting2': "アイヨン　リジョン",
        'dashboardSetting3': "シェタ　プロトコル",
        'dashboardUpdate': "アップデート",
        'dashboardFinished': "終わりましたか？",
        'dashboardLogout': "ログアウト",
        'alertOK': "はい",
    },
    'es': {
        'title': "AnyPhone",
        'numberDefault': "090-1234-5678",
        'enterPhone': "Introduce tu número",
        'enterPhoneExtra': "Este ejemplo está limitado a un número de 10-digitos (US)",
        'buttonSubmit': "Continuar",
        'buttonVerify': "Verificar",
        'warningPhone': "Debes introducir un número de 10 dígitos incluyendo su código de área (US)",
        'warningTwilio': "Algo salió mal. Por favor verifica tú configuración de Twilio.",
        'warningGeneral': "Algo salió mal. Por favor intenta de nuevo.",
        'warningNoNumber': "Olvidaste introducir tu número móvil.",
        'warningCodeLength': "Debes introducir el código de 4 dígitos que se envió a tu número telefónico.",
        'warningCodeInvalid': "Ese código de verificación no es válido.",
        'messageWelcomeDashboard': "Bienvenido a tu Panel de Control",
        'enterCode': "Introduce el código de confirmación de 4 dígitos",
        'enterCodeExtra': "Fue enviado en un mensaje de texto a",
        'emailLogin': "Tu código de inicio para AnyPhone es",
        'dashboardWelcome': "Bienvenido a tu Panel de Control",
        'dashboardNumber': "Tu número",
        'dashboardName': "Tu nombre",
        'dashboardNameHint': "Tony Stark",
        'dashboardSetting1': "Los Vengadores",
        'dashboardSetting2': "Liga de la Justicia",
        'dashboardSetting3': "Protocolo Omega",
        'dashboardUpdate': "Modificar",
        'dashboardFinished': "¿Terminaste?",
        'dashboardLogout': "Cerrar Sesión",
        'alertOK': "OK",
    },

};


module.exports = string;